openapi: 3.0.0
info:
  title: My personal library API
  description: |
    This API allows to maintain a personal book library
  version: 0.0.1
servers:
  - url: '/api/v1'
paths:
 # Whole books operations
  /books:
    get:
      summary: Get the all books
      description: Retrieves all the books from the database.
      tags:
        - Books
      operationId: getAllBooks
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                # no se si esta bien el path
                $ref: "./schemas/book-schema.json"
